# Config chung cho tất cả services
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    com.example: DEBUG
    org.springframework.cloud: INFO

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka