spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5435/user_service
    username: microservice_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # ĐỔI THÀNH create-drop (cho lần đầu)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka/
    defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    instance-id: user-service:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# XÓA HOÀN TOÀN CÁC DÒNG SAU:
# database-platform: org.hibernate.dialect.PostgreSQLDialect
# sql.init.platform: postgresql
# jpa.defer-datasource-initialization: true
# format_sql: true
# jdbc.lob.non_contextual_creation: true