spring:
  application:
    name: order-service
  datasource:
#    Config postgre in docker
#    url: jdbc:postgresql://postgres:5432/order_service
#    username: microservice_user
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # ĐỔI THÀNH create-drop (cho lần đầu)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: rabbitmq   # vì chạy trong docker-compose nên dùng tên service "rabbitmq"
    port: 5672
    username: admin
    password: admin

server:
  port: 8082

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka/
    defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    instance-id: order-service:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


# XÓA HOÀN TOÀN CÁC DÒNG SAU:
# database-platform: org.hibernate.dialect.PostgreSQLDialect
# sql.init.platform: postgresql
# jpa.defer-datasource-initialization: true
# format_sql: true
# jdbc.lob.non_contextual_creation: true