spring:
  application:
    name: application-user-service   # phải khớp với tên file config trên Config Server
  config:
    import: "optional:configserver:http://cloud-config-server:8888"
#    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
#      uri: http://cloud-config-server:8888   # URL Config Server
      fail-fast: true
      retry:
        initial-interval: 3000
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.5

# Logging bootstrap phase để debug
logging:
  level:
    org.springframework.cloud.config: INFO
    org.springframework.boot.context.config: INFO

jwt:
  secret: mySuperSecretKeyForJwt1234567890
  expiration-ms: 900000        # 15 minutes
  refresh-expiration-ms: 1209600000  # 14 days

resilience4j:
  circuitbreaker:
    instances:
      rabbitMqCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
